enable_all: true
#If enable_all is true this is ignored
#This means that if enable_all is true you can milk minecarts. Be warned.
enabled_entities:
    player: true
    bat: true
    cat: true
    chicken: true
    cod: true
    cow: true
    donkey: true
    fox: true
    horse: true
    mooshroom: true
    mule: true
    ocelot: true
    parrot: true
    pig: true
    piglin: true
    piglin_baby: true
    polar_bear: true
    polar_bear_baby: true
    pufferfish: true
    rabbit: true
    salmon: true
    sheep: true
    skeleton_horse: true
    snow_golem: true
    squid: true
    strider: true
    tropical_fish: true
    turtle: true
    villager: true
    wandering_trader: true
    bee: true
    cave_spider: true
    dolphin: true
    enderman: true
    iron_golem: true
    llama: true
    panda: true
    spider: true
    wolf: true
    zombified_piglin: true
    #hostile
    blaze: true
    chicken_jockey: true
    creeper: true
    drowned: true
    elder_guardian: true
    endermite: true
    evoker: true
    ghast: true
    guardian: true
    hoglin: true
    husk: true
    magma_cube: true
    phantom: true
    piglin_brute: true
    pillager: true
    ravager: true
    shulker: true
    silverfish: true
    skeleton: true
    slime: true
    stray: true
    vex: true
    vindicator: true
    witch: true
    wither_skeleton: true
    zoglin: true
    zombie: true
    zombie_villager: true

item_name: "%name%'s milk"